[MPIPreferences]
_format = "1.1"
abi = "MPICH"
binary = "system"
cclibs = []
libmpi = "libmpi_cray"
mpiexec = "mpiexec"
preloads = ["/opt/cray/pe/mpich/default/gtl/lib/libmpi_gtl_cuda.so"]
preloads_env_switch = "MPICH_GPU_SUPPORT_ENABLED"
