[CUDA_Runtime_jll]
__clear__ = ["local"]
version = "13.0"

[MPIPreferences]
_format = "1.1"
abi = "MPICH"
binary = "system"
cclibs = []
libmpi = "libmpi_cray"
mpiexec = "mpiexec"
preloads = []
preloads_env_switch = "MPICH_GPU_SUPPORT_ENABLED"
